variables:
  TZ: "Asia/Shanghai"
  MAVEN_CLI_OPTS: " --batch-mode"


stages:
  - buildOnJava17
  - buildOnJava11
  - deploy

buildOnJava11:
  image: maven:3.8.3-eclipse-temurin-11
  stage: buildOnJava11
  script:
    - mvn -v
    - keytool -keystore $JAVA_HOME/lib/security/cacerts -storepass changeit -noprompt -trustcacerts -importcert -alias guanaitongca -file .gitlab/GuanaitongCA.crt
    - mvn $MAVEN_CLI_OPTS test
    - mvn $MAVEN_CLI_OPTS verify sonar:sonar -Djacoco.skip=false

buildOnJava17:
  image: maven:3.8.3-eclipse-temurin-17
  stage: buildOnJava17
  script:
    - mvn -v
    - keytool -keystore $JAVA_HOME/lib/security/cacerts -storepass changeit -noprompt -trustcacerts -importcert -alias guanaitongca -file .gitlab/GuanaitongCA.crt
    - mvn $MAVEN_CLI_OPTS test -Djava.version=17
    - mvn $MAVEN_CLI_OPTS verify sonar:sonar  -Djacoco.skip=false -Djava.version=17

deploy:
  image: maven:3.8.3-eclipse-temurin-11
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS deploy -Dmaven.test.skip=true
    - sh generate_parent_pom.sh
    - mvn $MAVEN_CLI_OPTS -f tmp/.flattened-pom.xml -Dmaven.test.skip=true deploy
  only:
    - master
    - 2021.1.x
